services:
  app:
    container_name: weat-api-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: weat-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weat-db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

volumes:
  data:


networks:
  backend:
    driver: bridge
