"""Add unique index to google_maps_place_id in places

Revision ID: 28b82e7be236
Revises: 9e7065ffdcb0
Create Date: 2025-04-09 14:51:58.006675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b82e7be236'
down_revision: Union[str, None] = '9e7065ffdcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'places', ['google_maps_place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='unique')
    # ### end Alembic commands ###
