"""Allow multiple menus per place

Revision ID: b17d2f413e29
Revises: 8b260dc851ec
Create Date: 2025-05-11 15:26:38.016877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b17d2f413e29"
down_revision: Union[str, None] = "8b260dc851ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("menus_place_id_key", "menus", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove duplicate menus and only keep one
    op.execute(
        """
        DELETE FROM menus a USING (
            SELECT DISTINCT ON (place_id) id
            FROM menus
            ORDER BY place_id, created_at
        ) b
        WHERE a.id != b.id
    """
    )

    op.create_unique_constraint("menus_place_id_key", "menus", ["place_id"])
    # ### end Alembic commands ###
