"""Set default values for opening_hours and properties

Revision ID: c618f5880466
Revises: 1393d3c73e50
Create Date: 2025-04-18 14:55:21.530444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c618f5880466"
down_revision: Union[str, None] = "1393d3c73e50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE places SET opening_hours = '[]' WHERE opening_hours IS NULL")
    op.execute("UPDATE places SET properties = '{}' WHERE properties IS NULL")

    op.alter_column(
        "places",
        "opening_hours",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "places",
        "properties",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "places",
        "properties",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "places",
        "opening_hours",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
