openapi: "3.0.0"

info:
  title: Weat API
  version: "1.0"

tags:
  - name: Health
  - name: Restaurants
  - name: Restaurant Categories
  - name: Restaurant Items
  - name: Restaurant Item Categories

paths:
  ########## Health ##########
  /health:
    get:
      summary: Health check
      description: Returns the health status of the application.
      operationId: app.routes.health
      tags:
        - Health
      responses:
        "200":
          description: Healthy
          content:
            application/json:
              schema:
                type: string
                example: "OK"
      security: []

  ########## Restaurants ##########
  /restaurants:
    get:
      summary: List all restaurants
      description: Returns a list of all restaurants.
      operationId: app.routes.list_restaurants
      tags:
        - Restaurants
      parameters:
        - $ref: "#/components/parameters/Locale"
        - $ref: "#/components/parameters/Sort"
        - $ref: "#/components/parameters/Order"
      responses:
        "200":
          description: List of restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurant"
      security: []
    post:
      summary: Create a restaurant
      description: Creates a new restaurant.
      operationId: app.routes.create_restaurant
      tags:
        - Restaurants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantForm"
      responses:
        "201":
          description: Restaurant created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
      security: []
  /restaurants/{restaurant_id}:
    get:
      summary: Get a restaurant
      description: Returns a restaurant by ID.
      operationId: app.routes.get_restaurant
      tags:
        - Restaurants
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
        - $ref: "#/components/parameters/Locale"
      responses:
        "200":
          description: Restaurant found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        "404":
          description: Restaurant not found
      security: []
    put:
      summary: Update a restaurant
      description: Updates a restaurant by ID.
      operationId: app.routes.update_restaurant
      tags:
        - Restaurants
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantForm"
      responses:
        "200":
          description: Restaurant updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        "404":
          description: Restaurant not found
      security: []
    delete:
      summary: Delete a restaurant
      description: Deletes a restaurant by ID.
      operationId: app.routes.delete_restaurant
      tags:
        - Restaurants
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
      responses:
        "204":
          description: Restaurant deleted
      security: []

  ########## Restaurant Categories ##########
  /restaurants/categories:
    get:
      summary: List all restaurant categories
      description: Returns a list of all restaurant categories.
      operationId: app.routes.list_restaurant_categories
      tags:
        - Restaurant Categories
      parameters:
        - $ref: "#/components/parameters/Locale"
      responses:
        "200":
          description: List of restaurant categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RestaurantCategory"
      security: []
    post:
      summary: Create a restaurant category
      description: Creates a new restaurant category.
      operationId: app.routes.create_restaurant_category
      tags:
        - Restaurant Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantCategoryForm"
      responses:
        "201":
          description: Restaurant category created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantCategory"
      security: []
  /restaurants/categories/{category_id}:
    put:
      summary: Update a restaurant category
      description: Updates a restaurant category by ID.
      operationId: app.routes.update_restaurant_category
      tags:
        - Restaurant Categories
      parameters:
        - $ref: "#/components/parameters/RestaurantCategoryId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantCategoryForm"
      responses:
        "200":
          description: Restaurant category updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantCategory"
        "404":
          description: Restaurant category not found
      security: []
    delete:
      summary: Delete a restaurant category
      description: Deletes a restaurant category by ID.
      operationId: app.routes.delete_restaurant_category
      tags:
        - Restaurant Categories
      parameters:
        - $ref: "#/components/parameters/RestaurantCategoryId"
      responses:
        "204":
          description: Restaurant category deleted
      security: []

  ########## Restaurant Items ##########
  /restaurants/{restaurant_id}/items:
    get:
      summary: List all restaurant items
      description: Returns a list of all restaurant items.
      operationId: app.routes.list_restaurant_items
      tags:
        - Restaurant Items
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
        - $ref: "#/components/parameters/Locale"
      responses:
        "200":
          description: List of restaurant items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RestaurantItem"
      security: []
    post:
      summary: Create restaurant items
      description: Creates new restaurant item.
      operationId: app.routes.create_restaurant_items
      tags:
        - Restaurant Items
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/RestaurantItemForm"
      responses:
        "201":
          description: Restaurant item created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantItem"
      security: []
    delete:
      summary: Delete restaurant items
      description: Deletes all/selected restaurant items. If no item IDs are provided, all items will be deleted.
      operationId: app.routes.delete_restaurant_items
      tags:
        - Restaurant Items
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
      responses:
        "204":
          description: Restaurant items deleted
      security: []
  /restaurants/{restaurant_id}/items/{item_id}:
    get:
      summary: Get a restaurant item
      description: Returns a restaurant item by ID.
      operationId: app.routes.get_restaurant_item
      tags:
        - Restaurant Items
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
        - $ref: "#/components/parameters/RestaurantItemId"
        - $ref: "#/components/parameters/Locale"
      responses:
        "200":
          description: Restaurant item found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantItem"
        "404":
          description: Restaurant item not found
      security: []
    put:
      summary: Update a restaurant item
      description: Updates a restaurant item by ID.
      operationId: app.routes.update_restaurant_item
      tags:
        - Restaurant Items
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
        - $ref: "#/components/parameters/RestaurantItemId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantItemForm"
      responses:
        "200":
          description: Restaurant item updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantItem"
        "404":
          description: Restaurant item not found
      security: []
    delete:
      summary: Delete a restaurant item
      description: Deletes a restaurant item by ID.
      operationId: app.routes.delete_restaurant_item
      tags:
        - Restaurant Items
      parameters:
        - $ref: "#/components/parameters/RestaurantId"
        - $ref: "#/components/parameters/RestaurantItemId"
      responses:
        "204":
          description: Restaurant item deleted
      security: []

  ########## Restaurant Item Categories ##########
  /restaurants/{restaurant_id}/items/categories:
    get:
      summary: List all restaurant item categories
      description: Returns a list of all restaurant item categories.
      operationId: app.routes.list_restaurant_item_categories
      tags:
        - Restaurant Item Categories
      parameters:
        - $ref: "#/components/parameters/Locale"
        - $ref: "#/components/parameters/RestaurantId"
      responses:
        "200":
          description: List of restaurant item categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RestaurantItemCategory"
      security: []
    post:
      summary: Create a restaurant item category
      description: Creates a new restaurant item category.
      operationId: app.routes.create_restaurant_item_category
      tags:
        - Restaurant Item Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantItemCategoryForm"
      responses:
        "201":
          description: Restaurant item category created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantItemCategory"
      security: []
  /restaurants/{restaurant_id}/items/categories/{category_id}:
    put:
      summary: Update a restaurant item category
      description: Updates a restaurant item category by ID.
      operationId: app.routes.update_restaurant_item_category
      tags:
        - Restaurant Item Categories
      parameters:
        - $ref: "#/components/parameters/RestaurantItemCategoryId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantItemCategoryForm"
      responses:
        "200":
          description: Restaurant item category updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantItemCategory"
        "404":
          description: Restaurant item category not found
      security: []
    delete:
      summary: Delete a restaurant item category
      description: Deletes a restaurant item category by ID.
      operationId: app.routes.delete_restaurant_item_category
      tags:
        - Restaurant Item Categories
      parameters:
        - $ref: "#/components/parameters/RestaurantItemCategoryId"
      responses:
        "204":
          description: Restaurant item category deleted
      security: []

components:
  parameters:
    ########## Locale ##########
    Locale:
      name: locale
      in: query
      description: The selected locale for display
      required: false
      schema:
        type: string
        example: en
        default: en
    Sort:
      name: sort
      in: query
      description: The field to sort by
      required: false
      schema:
        type: string
        enum: [price, rating, num_items]
    Order:
      name: order
      in: query
      description: The order to sort by
      required: false
      schema:
        type: string
        enum: [asc, desc]

    ########## IDs ##########
    RestaurantId:
      name: restaurant_id
      in: path
      description: The ID of the restaurant
      required: true
      schema:
        type: string
        format: uuid
    RestaurantCategoryId:
      name: category_id
      in: query
      description: The ID of the restaurant category
      required: false
      schema:
        type: string
        format: uuid
    RestaurantItemId:
      name: item_id
      in: path
      description: The ID of the restaurant item
      required: true
      schema:
        type: string
        format: uuid
    RestaurantItemCategoryId:
      name: category_id
      in: path
      description: The ID of the restaurant item category
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    ########## Models ##########
    Restaurant:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          minLength: 1
        address:
          type: string
        price:
          type: integer
          minimum: 0
        rating:
          type: number
          minimum: 0
          maximum: 5
        images:
          type: array
          items:
            type: string
        url:
          type: string
        google_place_id:
          type: string
        categories:
          type: array
          items:
            $ref: "#/components/schemas/RestaurantCategory"
    RestaurantCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          minLength: 1
    RestaurantItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          minLength: 1
        description:
          type: string
        category:
          $ref: "#/components/schemas/RestaurantItemCategory"
        price:
          type: number
          minimum: 0
        image:
          type: string
    RestaurantItemCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          minLength: 1

    ########## Forms ##########
    RestaurantForm:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        address:
          type: string
        price:
          type: integer
          minimum: 0
        rating:
          type: number
          minimum: 0
          maximum: 5
        images:
          type: array
          items:
            type: string
        url:
          type: string
        google_place_id:
          type: string
        category_ids:
          type: array
          items:
            type: string
            format: uuid
        translations:
          type: object
          properties:
            zh-CN:
              $ref: "#/components/schemas/RestaurantTranslation"
            zh-TW:
              $ref: "#/components/schemas/RestaurantTranslation"
    RestaurantCategoryForm:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        translations:
          type: object
          properties:
            zh-CN:
              $ref: "#/components/schemas/RestaurantCategoryTranslation"
            zh-TW:
              $ref: "#/components/schemas/RestaurantCategoryTranslation"
    RestaurantItemForm:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
        category:
          $ref: "#/components/schemas/RestaurantItemCategory"
        price:
          type: number
          minimum: 0
        image:
          type: string
        translations:
          type: object
          properties:
            zh-CN:
              $ref: "#/components/schemas/RestaurantItemTranslation"
            zh-TW:
              $ref: "#/components/schemas/RestaurantItemTranslation"
    RestaurantItemCategoryForm:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        translations:
          type: object
          properties:
            zh-CN:
              $ref: "#/components/schemas/RestaurantItemCategoryTranslation"
            zh-TW:
              $ref: "#/components/schemas/RestaurantItemCategoryTranslation"

    ########## Translations ##########
    RestaurantTranslation:
      type: object
      properties:
        name:
          type: string
          minLength: 1
    RestaurantCategoryTranslation:
      type: object
      properties:
        name:
          type: string
          minLength: 1
    RestaurantItemTranslation:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
    RestaurantItemCategoryTranslation:
      type: object
      properties:
        name:
          type: string
          minLength: 1
