"""Add business_hours to restaurants

Revision ID: 7e4663bea36e
Revises: 3544986e9686
Create Date: 2024-04-20 15:17:44.892316

"""

import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7e4663bea36e"
down_revision = "3544986e9686"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "business_hours", postgresql.JSON(astext_type=sa.Text()), nullable=True
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.drop_column("business_hours")

    # ### end Alembic commands ###
