name: Weat API CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: weat_api_test
          POSTGRES_PASSWORD: ""
        ports: [ "5432:5432" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
