name: Run Python Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: test_db_username
      DB_PASSWORD: test_db_password
      DB_HOST: test_db_host
      DB_PORT: test_db_port
      DB_NAME: test_db_name
      AWS_REGION: test_aws_region
      AWS_AUTH_DOMAIN: test_aws_auth_domain
      AWS_COGNITO_CLIENT_ID: test_aws_cognito_client_id
      AWS_COGNITO_USER_POOL_ID: test_aws_cognito_user_pool_id

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/
